--- drivers/hid/Makefile
+++ drivers/hid/Makefile
@@ -183,3 +185,7 @@ obj-$(CONFIG_INTEL_THC_HID)     += intel-thc-hid/
 obj-$(CONFIG_SPI_HID_APPLE_CORE)	+= spi-hid/
 
 obj-$(CONFIG_HID_DOCKCHANNEL)   += dockchannel-hid/
+
+obj-$(CONFIG_HID_MSI_CLAW)      += hid-msi-claw.o
+
+obj-$(CONFIG_LENOVO_LEGOS_HID)  += lenovo-legos-hid/
