# SPDX-License-Identifier: GPL-2.0+
#
# Makefile - Lenovo Legion Go S Handheld Console Controller driver
#
lenovo-legos-hid-y := lenovo-legos-hid-core.o lenovo-legos-hid-config.o
obj-$(CONFIG_LENOVO_LEGOS_HID)	:= lenovo-legos-hid.o
